[msx] test Started org.apache.hadoop.hdfs.server.namenode.TestStorageRestore#testStorageRestoreFailure
[msx] unitTestCounterInClass = 0
2020-03-14 05:35:19,823 [main] INFO  namenode.NameNode (NameNode.java:<clinit>(931)) - [msx-restart] reconfPoint = 0
2020-03-14 05:35:20,742 [main] INFO  namenode.NameNode (NameNode.java:performReconfig(958)) - [msx-restart] NameNode init, reconfigMode is none, do nothing
2020-03-14 05:35:21,782 [main] INFO  namenode.NameNode (NameNode.java:<init>(1042)) - [msx-restart] NameNode 35661 start
2020-03-14 05:35:22,991 [main] INFO  namenode.NameNode (NameNode.java:stop(1087)) - [msx-restart] NameNode 35661 stop, double check before stop, dfs.data.transfer.client.tcpnodelay = true
[msx] test Failure org.apache.hadoop.hdfs.server.namenode.TestStorageRestore#testStorageRestoreFailure
[msx] writeFile testName = org.apache.hadoop.hdfs.server.namenode.TestStorageRestore#testStorageRestoreFailure
[msx] failed
[msx] failureMessage: null
[msx] stackTrace: java.lang.AssertionError
2020-03-14 05:35:23,099 [main] INFO  datanode.DataNode (DataNode.java:<clinit>(433)) - [msx-restart] reconfPoint = 0
2020-03-14 05:35:23,101 [main] INFO  server.JournalNode (JournalNode.java:<clinit>(168)) - [msx-restart] reconfPoint = 0
[msx] reset performed
[msx] test Finished org.apache.hadoop.hdfs.server.namenode.TestStorageRestore#testStorageRestoreFailure
[msx] writeFile testName = org.apache.hadoop.hdfs.server.namenode.TestStorageRestore#testStorageRestoreFailure
[msx] Info : file existed /root/parameter_test_controller/shared/test_results/org.apache.hadoop.hdfs.server.namenode.TestStorageRestore#testStorageRestoreFailure
[msx] succeed
[msx] reset performed
[msx] all testRunFinished
