[msx] before_class
[msx] test Started org.apache.hadoop.fs.TestEnhancedByteBufferAccess#test2GBMmapLimit
[msx] unitTestCounterInClass = 0
[msx] testAssumptionFailure org.apache.hadoop.fs.TestEnhancedByteBufferAccess#test2GBMmapLimit
[msx] writeFile testName = org.apache.hadoop.fs.TestEnhancedByteBufferAccess#test2GBMmapLimit
[msx] failed
[msx] failureMessage: got: <false>, expected: is <true>
[msx] stackTrace: org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>
2020-03-14 04:50:10,509 [main] INFO  namenode.NameNode (NameNode.java:<clinit>(931)) - [msx-restart] reconfPoint = 0
2020-03-14 04:50:10,542 [main] INFO  datanode.DataNode (DataNode.java:<clinit>(433)) - [msx-restart] reconfPoint = 0
2020-03-14 04:50:10,544 [main] INFO  server.JournalNode (JournalNode.java:<clinit>(168)) - [msx-restart] reconfPoint = 0
[msx] reset performed
[msx] test Finished org.apache.hadoop.fs.TestEnhancedByteBufferAccess#test2GBMmapLimit
[msx] writeFile testName = org.apache.hadoop.fs.TestEnhancedByteBufferAccess#test2GBMmapLimit
[msx] Info : file existed /root/parameter_test_controller/shared/test_results/org.apache.hadoop.fs.TestEnhancedByteBufferAccess#test2GBMmapLimit
[msx] succeed
[msx] reset performed
[msx] all testRunFinished
