[msx] test Started org.apache.hadoop.hdfs.web.TestWebHDFS#testDTInInsecureClusterWithFallback
[msx] unitTestCounterInClass = 0
2020-03-14 08:25:15,140 [main] INFO  namenode.NameNode (NameNode.java:<clinit>(931)) - [msx-restart] reconfPoint = 0
2020-03-14 08:25:15,978 [main] INFO  namenode.NameNode (NameNode.java:performReconfig(958)) - [msx-restart] NameNode init, reconfigMode is none, do nothing
2020-03-14 08:25:16,952 [main] INFO  namenode.NameNode (NameNode.java:<init>(1042)) - [msx-restart] NameNode 37928 start
2020-03-14 08:25:18,524 [main] INFO  namenode.NameNode (NameNode.java:stop(1087)) - [msx-restart] NameNode 37928 stop, double check before stop, dfs.data.transfer.client.tcpnodelay = true
[msx] test Finished org.apache.hadoop.hdfs.web.TestWebHDFS#testDTInInsecureClusterWithFallback
[msx] writeFile testName = org.apache.hadoop.hdfs.web.TestWebHDFS#testDTInInsecureClusterWithFallback
[msx] succeed
2020-03-14 08:25:18,621 [main] INFO  datanode.DataNode (DataNode.java:<clinit>(433)) - [msx-restart] reconfPoint = 0
2020-03-14 08:25:18,623 [main] INFO  server.JournalNode (JournalNode.java:<clinit>(168)) - [msx-restart] reconfPoint = 0
[msx] reset performed
[msx] all testRunFinished
