[msx] test Started org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailure#testDNFailToStartWithDataDirNonWritable
[msx] unitTestCounterInClass = 0
2020-03-14 07:38:30,497 [Thread-0] INFO  namenode.NameNode (NameNode.java:<clinit>(931)) - [msx-restart] reconfPoint = 0
2020-03-14 07:38:31,206 [Thread-0] INFO  namenode.NameNode (NameNode.java:performReconfig(958)) - [msx-restart] NameNode init, reconfigMode is none, do nothing
2020-03-14 07:38:32,279 [Thread-0] INFO  namenode.NameNode (NameNode.java:<init>(1042)) - [msx-restart] NameNode 42415 start
2020-03-14 07:38:32,294 [Thread-0] INFO  datanode.DataNode (DataNode.java:<clinit>(433)) - [msx-restart] reconfPoint = 0
2020-03-14 07:38:32,371 [Thread-0] INFO  datanode.DataNode (DataNode.java:performReconfig(460)) - [msx-restart] DataNode init, reconfigMode is none, do nothing
2020-03-14 07:38:32,594 [Thread-0] INFO  datanode.DataNode (DataNode.java:runDatanodeDaemon(2750)) - [msx-restart] DataNode 33849 start
2020-03-14 07:38:32,613 [Thread-0] INFO  datanode.DataNode (DataNode.java:performReconfig(460)) - [msx-restart] DataNode init, reconfigMode is none, do nothing
2020-03-14 07:38:32,665 [Thread-0] INFO  datanode.DataNode (DataNode.java:runDatanodeDaemon(2750)) - [msx-restart] DataNode 46681 start
2020-03-14 07:38:33,260 [Thread-119] INFO  datanode.DataNode (DataNode.java:performReconfig(460)) - [msx-restart] DataNode init, reconfigMode is none, do nothing
2020-03-14 07:38:33,300 [Thread-119] INFO  datanode.DataNode (DataNode.java:runDatanodeDaemon(2750)) - [msx-restart] DataNode 34344 start
2020-03-14 07:38:33,409 [Thread-0] INFO  datanode.DataNode (DataNode.java:shutdown(2075)) - [msx-restart] DataNode 34344 stop, double check before stop, dfs.data.transfer.client.tcpnodelay = true
2020-03-14 07:38:33,440 [Thread-0] INFO  datanode.DataNode (DataNode.java:shutdown(2075)) - [msx-restart] DataNode 46681 stop, double check before stop, dfs.data.transfer.client.tcpnodelay = true
2020-03-14 07:38:33,462 [Thread-0] INFO  datanode.DataNode (DataNode.java:shutdown(2075)) - [msx-restart] DataNode 33849 stop, double check before stop, dfs.data.transfer.client.tcpnodelay = true
2020-03-14 07:38:33,588 [Thread-0] INFO  namenode.NameNode (NameNode.java:stop(1087)) - [msx-restart] NameNode 42415 stop, double check before stop, dfs.data.transfer.client.tcpnodelay = true
[msx] test Failure org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailure#testDNFailToStartWithDataDirNonWritable
[msx] writeFile testName = org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailure#testDNFailToStartWithDataDirNonWritable
[msx] failed
[msx] failureMessage: Failed to get expected IOException
[msx] stackTrace: java.lang.AssertionError: Failed to get expected IOException
2020-03-14 07:38:33,661 [main] INFO  server.JournalNode (JournalNode.java:<clinit>(168)) - [msx-restart] reconfPoint = 0
[msx] reset performed
[msx] test Finished org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailure#testDNFailToStartWithDataDirNonWritable
[msx] writeFile testName = org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailure#testDNFailToStartWithDataDirNonWritable
[msx] Info : file existed /root/parameter_test_controller/shared/test_results/org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailure#testDNFailToStartWithDataDirNonWritable
[msx] succeed
[msx] reset performed
[msx] all testRunFinished
