[msx] test Started org.apache.hadoop.hdfs.server.datanode.TestDirectoryScanner#testExceptionHandlingWhileDirectoryScan
[msx] unitTestCounterInClass = 0
2020-03-14 07:46:59,966 [main] INFO  namenode.NameNode (NameNode.java:<clinit>(931)) - [msx-restart] reconfPoint = 0
2020-03-14 07:47:01,058 [Thread-1] INFO  namenode.NameNode (NameNode.java:performReconfig(958)) - [msx-restart] NameNode init, reconfigMode is none, do nothing
2020-03-14 07:47:02,126 [Thread-1] INFO  namenode.NameNode (NameNode.java:<init>(1042)) - [msx-restart] NameNode 42810 start
2020-03-14 07:47:02,143 [Thread-1] INFO  datanode.DataNode (DataNode.java:<clinit>(433)) - [msx-restart] reconfPoint = 0
2020-03-14 07:47:02,231 [Thread-1] INFO  datanode.DataNode (DataNode.java:performReconfig(460)) - [msx-restart] DataNode init, reconfigMode is none, do nothing
2020-03-14 07:47:02,593 [Thread-1] INFO  datanode.DataNode (DataNode.java:runDatanodeDaemon(2750)) - [msx-restart] DataNode 40431 start
2020-03-14 07:47:03,697 [Thread-1] INFO  datanode.DataNode (DataNode.java:shutdown(2075)) - [msx-restart] DataNode 40431 stop, double check before stop, dfs.data.transfer.client.tcpnodelay = true
2020-03-14 07:47:03,844 [Thread-1] INFO  namenode.NameNode (NameNode.java:stop(1087)) - [msx-restart] NameNode 42810 stop, double check before stop, dfs.data.transfer.client.tcpnodelay = true
[msx] test Finished org.apache.hadoop.hdfs.server.datanode.TestDirectoryScanner#testExceptionHandlingWhileDirectoryScan
[msx] writeFile testName = org.apache.hadoop.hdfs.server.datanode.TestDirectoryScanner#testExceptionHandlingWhileDirectoryScan
[msx] succeed
2020-03-14 07:47:03,909 [main] INFO  server.JournalNode (JournalNode.java:<clinit>(168)) - [msx-restart] reconfPoint = 0
[msx] reset performed
[msx] all testRunFinished
