[msx] test Started org.apache.hadoop.hdfs.server.datanode.TestBlockRecovery#testRecoveryInProgressException
[msx] unitTestCounterInClass = 0
2020-03-14 06:57:27,966 [main] INFO  datanode.DataNode (DataNode.java:<clinit>(433)) - [msx-restart] reconfPoint = 0
2020-03-14 06:57:27,970 [main] INFO  datanode.DataNode (DataNode.java:performReconfig(460)) - [msx-restart] DataNode init, reconfigMode is none, do nothing
2020-03-14 06:57:29,561 [main] INFO  datanode.DataNode (DataNode.java:shutdown(2075)) - [msx-restart] DataNode 0 stop, double check before stop, dfs.data.transfer.client.tcpnodelay = true
[msx] test Finished org.apache.hadoop.hdfs.server.datanode.TestBlockRecovery#testRecoveryInProgressException
[msx] writeFile testName = org.apache.hadoop.hdfs.server.datanode.TestBlockRecovery#testRecoveryInProgressException
[msx] succeed
2020-03-14 06:57:29,605 [main] INFO  namenode.NameNode (NameNode.java:<clinit>(931)) - [msx-restart] reconfPoint = 0
2020-03-14 06:57:29,607 [main] INFO  server.JournalNode (JournalNode.java:<clinit>(168)) - [msx-restart] reconfPoint = 0
[msx] reset performed
[msx] all testRunFinished
